# Generated by Django 4.1.3 on 2022-11-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=30, null=True)),
                ('checked_in', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'passenger',
                'managed': False,
            },
        ),
    ]
